# coding: utf-8

"""
    JUDILIBRE-public

    La Cour de cassation, dans le cadre de la refonte de son site Web, a initié le projet JUDILIBRE visant à la conception et au développement en interne d'un moteur de recherche dans le corpus jurisprudentiel, mettant celui-ci à disposition du public dans l'esprit du décret sur l'Open Data des décisions de justice.  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: sebastien.courvoisier@justice.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import judilibre_client
from judilibre_client.api.default_api import DefaultApi  # noqa: E501
from judilibre_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = judilibre_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_decision(self):
        """Test case for decision

        Permet de récupérer le contenu intégral d'une décision.  # noqa: E501
        """
        pass

    def test_export(self):
        """Test case for export

        Permet d'effectuer un export par lot de décisions de justice.  # noqa: E501
        """
        pass

    def test_healthcheck(self):
        """Test case for healthcheck

        Permet de récupérer l'état de disponibilité du service.  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Permet d'effectuer une recherche dans les données ouvertes des décisions de justice.  # noqa: E501
        """
        pass

    def test_stats(self):
        """Test case for stats

        Permet de récupérer des statistiques sur le contenu de la base JUDILIBRE.  # noqa: E501
        """
        pass

    def test_taxonomy(self):
        """Test case for taxonomy

        Permet de récupérer les listes des termes employés par le processus de recherche.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
