# coding: utf-8

# flake8: noqa

"""
    JUDILIBRE-public

    La Cour de cassation, dans le cadre de la refonte de son site Web, a initié le projet JUDILIBRE visant à la conception et au développement en interne d'un moteur de recherche dans le corpus jurisprudentiel, mettant celui-ci à disposition du public dans l'esprit du décret sur l'Open Data des décisions de justice.  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: sebastien.courvoisier@justice.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from judilibre_client.api.default_api import DefaultApi

# import ApiClient
from judilibre_client.api_client import ApiClient
from judilibre_client.configuration import Configuration
# import models into sdk package
